/*
 * Autonomous API
 * Building the next evolution of actionable AI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AutonomousGetResultResponseDataRun;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AutonomousGetResultResponseData
 */
public class AutonomousGetResultResponseDataTest {
    private final AutonomousGetResultResponseData model = new AutonomousGetResultResponseData();

    /**
     * Model tests for AutonomousGetResultResponseData
     */
    @Test
    public void testAutonomousGetResultResponseData() {
        // TODO: test AutonomousGetResultResponseData
    }

    /**
     * Test the property 'run'
     */
    @Test
    public void runTest() {
        // TODO: test run
    }

}
