/*
 * Autonomous API
 * Building the next evolution of actionable AI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FeedbackSubmissionRequest
 */
public class FeedbackSubmissionRequestTest {
    private final FeedbackSubmissionRequest model = new FeedbackSubmissionRequest();

    /**
     * Model tests for FeedbackSubmissionRequest
     */
    @Test
    public void testFeedbackSubmissionRequest() {
        // TODO: test FeedbackSubmissionRequest
    }

    /**
     * Test the property 'feedback'
     */
    @Test
    public void feedbackTest() {
        // TODO: test feedback
    }

}
