/*
 * Autonomous API
 * Building the next evolution of actionable AI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TaskExecuteResponseData
 */
public class TaskExecuteResponseDataTest {
    private final TaskExecuteResponseData model = new TaskExecuteResponseData();

    /**
     * Model tests for TaskExecuteResponseData
     */
    @Test
    public void testTaskExecuteResponseData() {
        // TODO: test TaskExecuteResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'streamingUrl'
     */
    @Test
    public void streamingUrlTest() {
        // TODO: test streamingUrl
    }

    /**
     * Test the property 'watchUrl'
     */
    @Test
    public void watchUrlTest() {
        // TODO: test watchUrl
    }

}
