/*
 * Autonomous API
 * Building the next evolution of actionable AI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AutonomousGetResultResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutonomousApi
 */
@Disabled
public class AutonomousApiTest {

    private static AutonomousApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AutonomousApi(apiClient);
    }

    /**
     * Get Autonomous Task Result
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResultTest() throws ApiException {
        String id = null;
        AutonomousGetResultResponse response = api.getResult(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Stop an Autonomous Task
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void terminateTaskTest() throws ApiException {
        String id = null;
        api.terminateTask(id)
                .execute();
        // TODO: test validations
    }

}
