/*
 * Autonomous API
 * Building the next evolution of actionable AI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ExtractionFromUrlRequest;
import com.konfigthis.client.model.ExtractionFromUrlResponse;
import com.konfigthis.client.model.ExtractionGetResultResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExtractionApi
 */
@Disabled
public class ExtractionApiTest {

    private static ExtractionApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ExtractionApi(apiClient);
    }

    /**
     * Extract data from a URL
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fromUrlTest() throws ApiException {
        String url = null;
        String query = null;
        String columns = null;
        Integer limit = null;
        String format = null;
        ExtractionFromUrlResponse response = api.fromUrl()
                .url(url)
                .query(query)
                .columns(columns)
                .limit(limit)
                .format(format)
                .execute();
        // TODO: test validations
    }

    /**
     * Get extraction result
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResultTest() throws ApiException {
        String id = null;
        ExtractionGetResultResponse response = api.getResult(id)
                .execute();
        // TODO: test validations
    }

}
