/*
 * Autonomous API
 * Building the next evolution of actionable AI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.ExtractionFromUrlRequest;
import com.konfigthis.client.model.ExtractionFromUrlResponse;
import com.konfigthis.client.model.ExtractionGetResultResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class ExtractionApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ExtractionApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public ExtractionApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getApiKeyAuth() == null) {
            throw new IllegalArgumentException("\"x-api-key\" is required but no API key was provided. Please set \"x-api-key\" with ApiClient#setApiKeyAuth(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call fromUrlCall(ExtractionFromUrlRequest extractionFromUrlRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = extractionFromUrlRequest;

        // create path and map variables
        String localVarPath = "/extract";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fromUrlValidateBeforeCall(ExtractionFromUrlRequest extractionFromUrlRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'extractionFromUrlRequest' is set
        if (extractionFromUrlRequest == null) {
            throw new ApiException("Missing the required parameter 'extractionFromUrlRequest' when calling fromUrl(Async)");
        }

        return fromUrlCall(extractionFromUrlRequest, _callback);

    }


    private ApiResponse<ExtractionFromUrlResponse> fromUrlWithHttpInfo(ExtractionFromUrlRequest extractionFromUrlRequest) throws ApiException {
        okhttp3.Call localVarCall = fromUrlValidateBeforeCall(extractionFromUrlRequest, null);
        Type localVarReturnType = new TypeToken<ExtractionFromUrlResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call fromUrlAsync(ExtractionFromUrlRequest extractionFromUrlRequest, final ApiCallback<ExtractionFromUrlResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = fromUrlValidateBeforeCall(extractionFromUrlRequest, _callback);
        Type localVarReturnType = new TypeToken<ExtractionFromUrlResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class FromUrlRequestBuilder {
        private String url;
        private String query;
        private String columns;
        private Integer limit;
        private String format;

        private FromUrlRequestBuilder() {
        }

        /**
         * Set url
         * @param url  (optional)
         * @return FromUrlRequestBuilder
         */
        public FromUrlRequestBuilder url(String url) {
            this.url = url;
            return this;
        }
        
        /**
         * Set query
         * @param query  (optional)
         * @return FromUrlRequestBuilder
         */
        public FromUrlRequestBuilder query(String query) {
            this.query = query;
            return this;
        }
        
        /**
         * Set columns
         * @param columns  (optional)
         * @return FromUrlRequestBuilder
         */
        public FromUrlRequestBuilder columns(String columns) {
            this.columns = columns;
            return this;
        }
        
        /**
         * Set limit
         * @param limit  (optional)
         * @return FromUrlRequestBuilder
         */
        public FromUrlRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Set format
         * @param format  (optional)
         * @return FromUrlRequestBuilder
         */
        public FromUrlRequestBuilder format(String format) {
            this.format = format;
            return this;
        }
        
        /**
         * Build call for fromUrl
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Data extracted successfully </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            ExtractionFromUrlRequest extractionFromUrlRequest = buildBodyParams();
            return fromUrlCall(extractionFromUrlRequest, _callback);
        }

        private ExtractionFromUrlRequest buildBodyParams() {
            ExtractionFromUrlRequest extractionFromUrlRequest = new ExtractionFromUrlRequest();
            extractionFromUrlRequest.url(this.url);
            extractionFromUrlRequest.query(this.query);
            extractionFromUrlRequest.columns(this.columns);
            extractionFromUrlRequest.limit(this.limit);
            if (this.format != null)
            extractionFromUrlRequest.format(ExtractionFromUrlRequest.FormatEnum.fromValue(this.format));
            return extractionFromUrlRequest;
        }

        /**
         * Execute fromUrl request
         * @return ExtractionFromUrlResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Data extracted successfully </td><td>  -  </td></tr>
         </table>
         */
        public ExtractionFromUrlResponse execute() throws ApiException {
            ExtractionFromUrlRequest extractionFromUrlRequest = buildBodyParams();
            ApiResponse<ExtractionFromUrlResponse> localVarResp = fromUrlWithHttpInfo(extractionFromUrlRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute fromUrl request with HTTP info returned
         * @return ApiResponse&lt;ExtractionFromUrlResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Data extracted successfully </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<ExtractionFromUrlResponse> executeWithHttpInfo() throws ApiException {
            ExtractionFromUrlRequest extractionFromUrlRequest = buildBodyParams();
            return fromUrlWithHttpInfo(extractionFromUrlRequest);
        }

        /**
         * Execute fromUrl request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Data extracted successfully </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ExtractionFromUrlResponse> _callback) throws ApiException {
            ExtractionFromUrlRequest extractionFromUrlRequest = buildBodyParams();
            return fromUrlAsync(extractionFromUrlRequest, _callback);
        }
    }

    /**
     * Extract data from a URL
     * 
     * @param extractionFromUrlRequest  (required)
     * @return FromUrlRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Data extracted successfully </td><td>  -  </td></tr>
     </table>
     */
    public FromUrlRequestBuilder fromUrl() throws IllegalArgumentException {
        return new FromUrlRequestBuilder();
    }
    private okhttp3.Call getResultCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/extract/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getResultValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getResult(Async)");
        }

        return getResultCall(id, _callback);

    }


    private ApiResponse<ExtractionGetResultResponse> getResultWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getResultValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<ExtractionGetResultResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getResultAsync(String id, final ApiCallback<ExtractionGetResultResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getResultValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<ExtractionGetResultResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetResultRequestBuilder {
        private final String id;

        private GetResultRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Build call for getResult
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Extraction result retrieved successfully </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getResultCall(id, _callback);
        }


        /**
         * Execute getResult request
         * @return ExtractionGetResultResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Extraction result retrieved successfully </td><td>  -  </td></tr>
         </table>
         */
        public ExtractionGetResultResponse execute() throws ApiException {
            ApiResponse<ExtractionGetResultResponse> localVarResp = getResultWithHttpInfo(id);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getResult request with HTTP info returned
         * @return ApiResponse&lt;ExtractionGetResultResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Extraction result retrieved successfully </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<ExtractionGetResultResponse> executeWithHttpInfo() throws ApiException {
            return getResultWithHttpInfo(id);
        }

        /**
         * Execute getResult request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Extraction result retrieved successfully </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ExtractionGetResultResponse> _callback) throws ApiException {
            return getResultAsync(id, _callback);
        }
    }

    /**
     * Get extraction result
     * 
     * @param id  (required)
     * @return GetResultRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Extraction result retrieved successfully </td><td>  -  </td></tr>
     </table>
     */
    public GetResultRequestBuilder getResult(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new GetResultRequestBuilder(id);
    }
}
