/*
 * Autonomous API
 * Building the next evolution of actionable AI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.FeedbackSubmissionRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class FeedbackApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public FeedbackApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public FeedbackApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getApiKeyAuth() == null) {
            throw new IllegalArgumentException("\"x-api-key\" is required but no API key was provided. Please set \"x-api-key\" with ApiClient#setApiKeyAuth(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call submissionCall(String id, FeedbackSubmissionRequest feedbackSubmissionRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = feedbackSubmissionRequest;

        // create path and map variables
        String localVarPath = "/autonomous/{id}/feedback"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call submissionValidateBeforeCall(String id, FeedbackSubmissionRequest feedbackSubmissionRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling submission(Async)");
        }

        // verify the required parameter 'feedbackSubmissionRequest' is set
        if (feedbackSubmissionRequest == null) {
            throw new ApiException("Missing the required parameter 'feedbackSubmissionRequest' when calling submission(Async)");
        }

        return submissionCall(id, feedbackSubmissionRequest, _callback);

    }


    private ApiResponse<Void> submissionWithHttpInfo(String id, FeedbackSubmissionRequest feedbackSubmissionRequest) throws ApiException {
        okhttp3.Call localVarCall = submissionValidateBeforeCall(id, feedbackSubmissionRequest, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call submissionAsync(String id, FeedbackSubmissionRequest feedbackSubmissionRequest, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = submissionValidateBeforeCall(id, feedbackSubmissionRequest, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class SubmissionRequestBuilder {
        private final String id;
        private Boolean feedback;

        private SubmissionRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Set feedback
         * @param feedback  (optional)
         * @return SubmissionRequestBuilder
         */
        public SubmissionRequestBuilder feedback(Boolean feedback) {
            this.feedback = feedback;
            return this;
        }
        
        /**
         * Build call for submission
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Feedback received successfully </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            FeedbackSubmissionRequest feedbackSubmissionRequest = buildBodyParams();
            return submissionCall(id, feedbackSubmissionRequest, _callback);
        }

        private FeedbackSubmissionRequest buildBodyParams() {
            FeedbackSubmissionRequest feedbackSubmissionRequest = new FeedbackSubmissionRequest();
            feedbackSubmissionRequest.feedback(this.feedback);
            return feedbackSubmissionRequest;
        }

        /**
         * Execute submission request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Feedback received successfully </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            FeedbackSubmissionRequest feedbackSubmissionRequest = buildBodyParams();
            submissionWithHttpInfo(id, feedbackSubmissionRequest);
        }

        /**
         * Execute submission request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Feedback received successfully </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            FeedbackSubmissionRequest feedbackSubmissionRequest = buildBodyParams();
            return submissionWithHttpInfo(id, feedbackSubmissionRequest);
        }

        /**
         * Execute submission request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Feedback received successfully </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            FeedbackSubmissionRequest feedbackSubmissionRequest = buildBodyParams();
            return submissionAsync(id, feedbackSubmissionRequest, _callback);
        }
    }

    /**
     * Provide Feedback for an Autonomous Task
     * 
     * @param id  (required)
     * @param feedbackSubmissionRequest  (required)
     * @return SubmissionRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Feedback received successfully </td><td>  -  </td></tr>
     </table>
     */
    public SubmissionRequestBuilder submission(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new SubmissionRequestBuilder(id);
    }
}
