/*
 * Autonomous API
 * Building the next evolution of actionable AI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.TaskExecuteRequest;
import com.konfigthis.client.model.TaskExecuteResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class TaskApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TaskApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public TaskApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getApiKeyAuth() == null) {
            throw new IllegalArgumentException("\"x-api-key\" is required but no API key was provided. Please set \"x-api-key\" with ApiClient#setApiKeyAuth(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call executeCall(TaskExecuteRequest taskExecuteRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = taskExecuteRequest;

        // create path and map variables
        String localVarPath = "/autonomous";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call executeValidateBeforeCall(TaskExecuteRequest taskExecuteRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'taskExecuteRequest' is set
        if (taskExecuteRequest == null) {
            throw new ApiException("Missing the required parameter 'taskExecuteRequest' when calling execute(Async)");
        }

        return executeCall(taskExecuteRequest, _callback);

    }


    private ApiResponse<TaskExecuteResponse> executeWithHttpInfo(TaskExecuteRequest taskExecuteRequest) throws ApiException {
        okhttp3.Call localVarCall = executeValidateBeforeCall(taskExecuteRequest, null);
        Type localVarReturnType = new TypeToken<TaskExecuteResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call executeAsync(TaskExecuteRequest taskExecuteRequest, final ApiCallback<TaskExecuteResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = executeValidateBeforeCall(taskExecuteRequest, _callback);
        Type localVarReturnType = new TypeToken<TaskExecuteResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ExecuteRequestBuilder {
        private String task;

        private ExecuteRequestBuilder() {
        }

        /**
         * Set task
         * @param task  (optional)
         * @return ExecuteRequestBuilder
         */
        public ExecuteRequestBuilder task(String task) {
            this.task = task;
            return this;
        }
        
        /**
         * Build call for execute
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Task executed successfully </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            TaskExecuteRequest taskExecuteRequest = buildBodyParams();
            return executeCall(taskExecuteRequest, _callback);
        }

        private TaskExecuteRequest buildBodyParams() {
            TaskExecuteRequest taskExecuteRequest = new TaskExecuteRequest();
            taskExecuteRequest.task(this.task);
            return taskExecuteRequest;
        }

        /**
         * Execute execute request
         * @return TaskExecuteResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Task executed successfully </td><td>  -  </td></tr>
         </table>
         */
        public TaskExecuteResponse execute() throws ApiException {
            TaskExecuteRequest taskExecuteRequest = buildBodyParams();
            ApiResponse<TaskExecuteResponse> localVarResp = executeWithHttpInfo(taskExecuteRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute execute request with HTTP info returned
         * @return ApiResponse&lt;TaskExecuteResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Task executed successfully </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<TaskExecuteResponse> executeWithHttpInfo() throws ApiException {
            TaskExecuteRequest taskExecuteRequest = buildBodyParams();
            return executeWithHttpInfo(taskExecuteRequest);
        }

        /**
         * Execute execute request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Task executed successfully </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<TaskExecuteResponse> _callback) throws ApiException {
            TaskExecuteRequest taskExecuteRequest = buildBodyParams();
            return executeAsync(taskExecuteRequest, _callback);
        }
    }

    /**
     * Execute an Autonomous Task
     * 
     * @param taskExecuteRequest  (required)
     * @return ExecuteRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task executed successfully </td><td>  -  </td></tr>
     </table>
     */
    public ExecuteRequestBuilder execute() throws IllegalArgumentException {
        return new ExecuteRequestBuilder();
    }
}
